[2023-02-15T15:50:53.047+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: abc.test_airflow manual__2023-02-15T15:50:51.911279+00:00 [queued]>
[2023-02-15T15:50:53.059+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: abc.test_airflow manual__2023-02-15T15:50:51.911279+00:00 [queued]>
[2023-02-15T15:50:53.060+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-15T15:50:53.061+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-02-15T15:50:53.062+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-15T15:50:53.080+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): test_airflow> on 2023-02-15 15:50:51.911279+00:00
[2023-02-15T15:50:53.088+0000] {standard_task_runner.py:55} INFO - Started process 42555 to run task
[2023-02-15T15:50:53.093+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'abc', 'test_***', 'manual__2023-02-15T15:50:51.911279+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/dag_qatoffside.py', '--cfg-path', '/tmp/tmpuynr7p_g']
[2023-02-15T15:50:53.095+0000] {standard_task_runner.py:83} INFO - Job 66: Subtask test_***
[2023-02-15T15:50:53.184+0000] {task_command.py:389} INFO - Running <TaskInstance: abc.test_airflow manual__2023-02-15T15:50:51.911279+00:00 [running]> on host 55b685598511
[2023-02-15T15:50:53.273+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=abc
AIRFLOW_CTX_TASK_ID=test_***
AIRFLOW_CTX_EXECUTION_DATE=2023-02-15T15:50:51.911279+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-15T15:50:51.911279+00:00
[2023-02-15T15:50:53.276+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-15T15:50:53.277+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/dags/scraper_specific.py']
[2023-02-15T15:50:53.293+0000] {subprocess.py:86} INFO - Output:
[2023-02-15T15:50:56.752+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-02-15T15:50:56.753+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scraper_specific.py", line 4, in <module>
[2023-02-15T15:50:56.755+0000] {subprocess.py:93} INFO -     import snowflake.connector
[2023-02-15T15:50:56.756+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'snowflake'
[2023-02-15T15:50:56.853+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-02-15T15:50:56.872+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-02-15T15:50:56.878+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=abc, task_id=test_***, execution_date=20230215T155051, start_date=20230215T155053, end_date=20230215T155056
[2023-02-15T15:50:56.899+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 66 for task test_*** (Bash command failed. The command returned a non-zero exit code 1.; 42555)
[2023-02-15T15:50:56.932+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-15T15:50:56.975+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
